version: '3'
services:
  spam_detection:
    container_name: spam_detector_app
    build: .
    image: spam_detector_container:1
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    command: gunicorn -b :5000 -w 1 app:app